/* MolPath Simulator v2.5.0a — responsive tablet/mobile shell
   Layout/CSS unchanged from v2.4.0z21; compact-shell copy now resolves through the central i18n core. */
(function(){
'use strict';
const VERSION='v2.5.0a';
const COMPACT='(max-width: 1400px)';
const SRC={menu:'Menü',overview:'Übersicht',score:'Score',cart:'Auswahl',close:'Schließen',dash:'Übersicht & Lernpfad'};
function t(k){
  const source=SRC[k]||k;
  try{
    if(window.MolPathI18n&&typeof window.MolPathI18n.translate==='function'){
      const lang=typeof window.MolPathI18n.currentLang==='function'?window.MolPathI18n.currentLang():(localStorage.getItem('molpath_lang')||'de');
      return window.MolPathI18n.translate(source,lang)||source;
    }
  }catch(_){ }
  return source;
}
function q(s,r=document){return r.querySelector(s)}
function qa(s,r=document){return Array.from(r.querySelectorAll(s))}
function compact(){try{return matchMedia(COMPACT).matches}catch(_){return innerWidth<=1400}}
function addStyles(){if(document.getElementById('mp21-responsive-styles'))return;const s=document.createElement('style');s.id='mp21-responsive-styles';s.textContent=`
html,body{max-width:100%;overflow-x:hidden}.app,.main,.layout,.order-layout,#content{min-width:0}.main{box-sizing:border-box}.main img,#content img{max-width:100%;height:auto}.main canvas,#content canvas{max-width:100%!important}.mp21-table-scroll{max-width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.mp21-table-scroll>table{min-width:100%;width:max-content;max-width:none}.mp21-backdrop{display:none}.mp21-compactbar{display:none}.mp21-sheet-head{display:none}.mp21-sidebar-close,.mp21-sheet-close{display:none}
@media(max-width:1400px){
  body{overscroll-behavior-x:none}.app{display:block!important;grid-template-columns:none!important;width:100%!important;min-height:100dvh}.main{width:100%!important;max-width:none!important;padding:12px!important;margin:0!important}
  .sidebar{position:fixed!important;z-index:1200!important;left:0!important;top:0!important;bottom:0!important;width:min(390px,90vw)!important;max-width:90vw!important;height:100dvh!important;overflow:auto!important;border-right:1px solid var(--line)!important;border-bottom:0!important;padding:16px!important;transform:translateX(-105%);transition:transform .22s ease;box-shadow:0 20px 50px rgba(15,35,55,.22)}
  body.mp21-nav-open .sidebar{transform:translateX(0)}
  .mp21-sidebar-close{display:grid;place-items:center;position:sticky;top:0;z-index:2;margin:0 0 10px auto;width:42px;height:42px;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--text);font-size:1.25rem;font-weight:900;box-shadow:0 6px 16px rgba(15,35,55,.08);cursor:pointer}
  .mp21-backdrop{position:fixed;z-index:1100;inset:0;background:rgba(11,27,52,.38);backdrop-filter:blur(2px)}
  body.mp21-nav-open .mp21-backdrop,body.mp21-score-open .mp21-backdrop,body.mp21-cart-open .mp21-backdrop,body.mp21-dash-open .mp21-backdrop{display:block}
  .mp21-compactbar{display:flex;position:sticky;top:0;z-index:950;align-items:center;gap:8px;min-height:54px;margin:-12px -12px 10px;padding:7px 10px;background:rgba(247,251,254,.96);border-bottom:1px solid var(--line);box-shadow:0 7px 20px rgba(15,35,55,.08);backdrop-filter:blur(10px)}
  .mp21-tool{flex:0 0 auto;min-width:42px;height:40px;padding:0 10px;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--primary);font-weight:900;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:5px}.mp21-tool:active{transform:translateY(1px)}.mp21-tool[hidden]{display:none!important}.mp21-tool-icon{font-size:1.05rem;line-height:1}.mp21-tool-value{font-size:.78rem;white-space:nowrap}
  .mp21-case-title{min-width:0;flex:1;font-size:.86rem;font-weight:900;color:var(--text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:0 4px}
  .hero{display:block!important;grid-template-columns:none!important;margin:0 0 10px!important}.hero>.panel{padding:13px 15px!important}.hero>.kpi{display:none!important}.hero h2{font-size:1.35rem!important;margin:4px 0!important}.hero p{font-size:.82rem!important}.hero .badge{font-size:.68rem!important}
  .layout,.order-layout{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:12px!important;width:100%!important}.layout>#content,.order-layout>*{min-width:0!important}
  .section{padding:14px!important}.section-title{flex-wrap:wrap!important;align-items:flex-start!important}.section-title>div{min-width:0;flex:1}.section-title .btn{max-width:100%}
  .order-toolbar{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))!important}.info-grid{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))!important}
  .mp24-grid-2,.mp24-grid-3,.mp24-grid-results,.lab24-kpi-grid,.lab24-qc-grid,.lab24-reasoning-evidence,.lab24-capa-flow,.lab24-investigation-grid,.lab24-audit-grid,.lab24-media-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}
  .z11-top-timeline,.mp24c-top-timeline,.lab24-top-timeline{max-width:100%!important;overflow-x:auto!important;overscroll-behavior-x:contain!important}
  #scorecard,.cart,#mp21DashboardHost{position:fixed!important;z-index:1250!important;left:50%!important;right:auto!important;bottom:10px!important;top:auto!important;width:min(680px,calc(100vw - 20px))!important;max-width:calc(100vw - 20px)!important;max-height:84dvh!important;overflow:auto!important;margin:0!important;border-radius:18px!important;box-shadow:0 24px 64px rgba(11,27,52,.28)!important;transition:transform .22s ease,opacity .18s ease;opacity:0;visibility:hidden;pointer-events:none;transform:translate(-50%,calc(100% + 28px))!important;background:var(--panel)!important}
  body.mp21-score-open #scorecard{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,0)!important}
  body.mp21-cart-open .cart{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,0)!important}
  body.mp21-dash-open #mp21DashboardHost{opacity:1;visibility:visible;pointer-events:auto;transform:translate(-50%,0)!important}
  #mp21DashboardHost{padding:12px!important}.mp21-sheet-head{display:flex!important;position:sticky;top:-12px;z-index:5;align-items:center;justify-content:space-between;gap:10px;margin:-12px -12px 12px;padding:10px 12px;background:rgba(255,255,255,.97);border-bottom:1px solid var(--line);backdrop-filter:blur(8px)}.mp21-sheet-head b{font-size:.92rem}.mp21-sheet-close{display:grid;place-items:center;width:38px;height:38px;border:1px solid var(--line);border-radius:11px;background:#fff;color:var(--text);font-size:1.1rem;font-weight:900;cursor:pointer}
  #scorecard>.mp21-sheet-close,.cart>.mp21-sheet-close{display:grid;position:sticky;top:0;z-index:6;margin:-6px 0 4px auto}
  #v20bHomeDashboard,#courseDashboard{margin-left:0!important;margin-right:0!important}.v20b-dashboard,.course-dashboard{box-shadow:none!important}
}
@media(max-width:760px){
  .main{padding:9px!important}.mp21-compactbar{margin:-9px -9px 9px;padding:6px 7px;gap:5px}.mp21-tool{min-width:39px;height:38px;padding:0 8px}.mp21-case-title{font-size:.79rem}.mp21-tool-value.mp21-hide-phone{display:none}
  .sidebar{width:min(360px,94vw)!important;max-width:94vw!important;padding:12px!important}.brand{grid-template-columns:72px 1fr!important}.brand img{width:72px!important;height:72px!important}.powered{margin-left:86px!important}
  .hero>.panel{padding:11px 12px!important}.hero h2{font-size:1.18rem!important}.section{padding:12px!important}.box{padding:14px!important}
  .order-toolbar,.info-grid,.mp24-grid-2,.mp24-grid-3,.mp24-grid-results,.lab24-kpi-grid,.lab24-qc-grid,.lab24-reasoning-evidence,.lab24-capa-flow,.lab24-investigation-grid,.lab24-audit-grid,.lab24-media-grid{grid-template-columns:minmax(0,1fr)!important}
  .table th,.table td{padding:8px 9px}.contact{grid-template-columns:58px 1fr!important}.contact img{width:58px!important;height:72px!important}
  #scorecard,.cart,#mp21DashboardHost{bottom:6px!important;width:calc(100vw - 12px)!important;max-width:calc(100vw - 12px)!important;max-height:88dvh!important;border-radius:16px!important}
}
@media(min-width:1401px){#mp21DashboardHost{display:contents!important}}
`;
document.head.appendChild(s)}
function closeAll(){document.body.classList.remove('mp21-nav-open','mp21-score-open','mp21-cart-open','mp21-dash-open')}
function openOnly(cls){const on=document.body.classList.contains(cls);closeAll();if(!on)document.body.classList.add(cls)}
function makeButton(id,icon,title,extra=''){let b=document.getElementById(id);if(b)return b;b=document.createElement('button');b.type='button';b.id=id;b.className='mp21-tool '+extra;b.innerHTML=`<span class="mp21-tool-icon">${icon}</span>`;b.addEventListener('click',()=>{});b.title=title;b.setAttribute('aria-label',title);return b}
function ensureBackdrop(){let d=document.getElementById('mp21Backdrop');if(!d){d=document.createElement('div');d.id='mp21Backdrop';d.className='mp21-backdrop';d.addEventListener('click',closeAll);document.body.appendChild(d)}return d}
function ensureSidebar(){const sb=q('.sidebar');if(!sb)return;let c=q('#mp21NavClose',sb);if(!c){c=document.createElement('button');c.id='mp21NavClose';c.type='button';c.className='mp21-sidebar-close';c.textContent='×';c.addEventListener('click',closeAll);sb.insertBefore(c,sb.firstChild)}c.title=t('close');c.setAttribute('aria-label',t('close'));if(!sb.dataset.mp21Events){sb.dataset.mp21Events='1';sb.addEventListener('click',e=>{if(e.target.closest('.mini-case'))setTimeout(closeAll,0)});sb.addEventListener('change',e=>{if(e.target&&e.target.id==='caseSelect')setTimeout(closeAll,0)})}}
function ensureBar(){const main=q('.main');if(!main)return null;let bar=document.getElementById('mp21CompactBar');if(!bar){bar=document.createElement('div');bar.id='mp21CompactBar';bar.className='mp21-compactbar';bar.innerHTML=`<button type="button" class="mp21-tool" id="mp21MenuBtn"><span class="mp21-tool-icon">☰</span></button><div class="mp21-case-title" id="mp21CaseTitle"></div><button type="button" class="mp21-tool" id="mp21DashBtn"><span class="mp21-tool-icon">▦</span><span class="mp21-tool-value mp21-hide-phone" id="mp21DashLabel"></span></button><button type="button" class="mp21-tool" id="mp21ScoreBtn"><span class="mp21-tool-icon">★</span><span class="mp21-tool-value" id="mp21ScoreValue">0%</span></button><button type="button" class="mp21-tool" id="mp21CartBtn"><span class="mp21-tool-icon">🧪</span><span class="mp21-tool-value" id="mp21CartValue">0</span></button>`;main.insertBefore(bar,main.firstChild);q('#mp21MenuBtn',bar).addEventListener('click',()=>openOnly('mp21-nav-open'));q('#mp21DashBtn',bar).addEventListener('click',()=>openOnly('mp21-dash-open'));q('#mp21ScoreBtn',bar).addEventListener('click',()=>openOnly('mp21-score-open'));q('#mp21CartBtn',bar).addEventListener('click',()=>openOnly('mp21-cart-open'))}return bar}
function ensureDashHost(){const main=q('.main'),steps=document.getElementById('steps');if(!main)return null;let host=document.getElementById('mp21DashboardHost');if(!host){host=document.createElement('div');host.id='mp21DashboardHost';const anchor=document.getElementById('v20bHomeDashboard')||document.getElementById('courseDashboard')||steps;main.insertBefore(host,anchor||main.firstChild)}let head=q('.mp21-sheet-head',host);if(!head){head=document.createElement('div');head.className='mp21-sheet-head';head.innerHTML='<b id="mp21DashTitle"></b><button type="button" class="mp21-sheet-close" id="mp21DashClose">×</button>';host.insertBefore(head,host.firstChild);q('#mp21DashClose',head).addEventListener('click',closeAll)}const home=document.getElementById('v20bHomeDashboard'),course=document.getElementById('courseDashboard');[home,course].filter(Boolean).forEach(el=>{if(el.parentElement!==host)host.appendChild(el)});q('#mp21DashTitle',host).textContent=t('dash');const close=q('#mp21DashClose',host);if(close){close.title=t('close');close.setAttribute('aria-label',t('close'))}if(!host.dataset.mp21Events){host.dataset.mp21Events='1';host.addEventListener('click',e=>{const x=e.target.closest('[onclick]');if(x&&/v16(?:SwitchToCase|ContinueCourse|NextCourseCase)/.test(x.getAttribute('onclick')||''))setTimeout(closeAll,0)})}return host}
function ensureSheetClose(root,id){if(!root)return;let b=q('#'+id,root);if(!b){b=document.createElement('button');b.type='button';b.id=id;b.className='mp21-sheet-close';b.textContent='×';b.addEventListener('click',closeAll);root.insertBefore(b,root.firstChild)}b.title=t('close');b.setAttribute('aria-label',t('close'))}
function syncTables(){if(compact()){qa('#content table').forEach(table=>{if(table.parentElement&&table.parentElement.classList.contains('mp21-table-scroll'))return;const w=document.createElement('div');w.className='mp21-table-scroll';table.parentNode.insertBefore(w,table);w.appendChild(table)})}else{qa('#content .mp21-table-scroll').forEach(w=>{const table=q('table',w);if(table&&w.parentNode){w.parentNode.insertBefore(table,w);w.remove()}})}}
function updateBar(){const bar=ensureBar();if(!bar)return;const title=q('#mp21CaseTitle',bar);try{title.textContent=(typeof activeCase!=='undefined'&&activeCase)?(activeCase.short||activeCase.title||activeCase.id):'MolPath Simulator'}catch(_){title.textContent='MolPath Simulator'}const menu=q('#mp21MenuBtn',bar),dash=q('#mp21DashBtn',bar),score=q('#mp21ScoreBtn',bar),cart=q('#mp21CartBtn',bar);menu.title=t('menu');menu.setAttribute('aria-label',t('menu'));dash.title=t('overview');dash.setAttribute('aria-label',t('overview'));score.title=t('score');score.setAttribute('aria-label',t('score'));cart.title=t('cart');cart.setAttribute('aria-label',t('cart'));q('#mp21DashLabel',bar).textContent=t('overview');const k=document.getElementById('kScore');q('#mp21ScoreValue',bar).textContent=(k&&k.textContent.trim())||'—';let n=0;try{n=state&&state.selected?state.selected.size:0}catch(_){}q('#mp21CartValue',bar).textContent=String(n);const hasCart=!!q('.cart');cart.hidden=!hasCart;const hasDash=!!(document.getElementById('v20bHomeDashboard')||document.getElementById('courseDashboard'));dash.hidden=!hasDash}
function stamp(){try{window.MOLPATH_APP_VERSION=VERSION;document.title='MolPath Simulator '+VERSION;const els=[document.getElementById('v20bVersion'),document.getElementById('versionBadge'),...qa('.v20b-topstatus .v20b-pill.primary')].filter(Boolean);els.forEach(el=>{el.setAttribute('data-i18n-skip','1');el.textContent=VERSION})}catch(_){}}
function postRender(){addStyles();ensureBackdrop();ensureSidebar();ensureDashHost();ensureSheetClose(document.getElementById('scorecard'),'mp21ScoreClose');const cart=q('.cart');if(cart)ensureSheetClose(cart,'mp21CartClose');syncTables();updateBar();stamp();if(compact()){if(!cart)document.body.classList.remove('mp21-cart-open')}else closeAll()}
function installRenderHook(){try{const prev=window.render;if(typeof prev==='function'&&!prev.__mp21){const wrapped=function(){const out=prev.apply(this,arguments);postRender();return out};wrapped.__mp21=true;window.render=wrapped;try{render=wrapped}catch(_){}}}catch(_){} }
function boot(){addStyles();ensureBackdrop();ensureSidebar();ensureBar();ensureDashHost();installRenderHook();try{if(typeof window.render==='function')window.render()}catch(e){console.warn('[MolPath '+VERSION+'] render refresh failed',e)}postRender();try{matchMedia(COMPACT).addEventListener('change',()=>{closeAll();postRender()})}catch(_){window.addEventListener('resize',()=>{if(!compact())closeAll()})}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});}
const PREV_AFTER=window.MolPathI18nAfterApply;window.MolPathI18nAfterApply=function(x){try{if(typeof PREV_AFTER==='function')PREV_AFTER(x)}catch(_){}setTimeout(postRender,0)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0);
window.MolPathResponsiveShell=Object.freeze({version:VERSION,base:'v2.4.0z21',breakpoint:1400,closeAll,postRender});
})();
